### ISSUE TITLE
Cannot run in 4.1.0 redmine.

### ISSUE THREAD

**Issue by CNPF** [HugoHasenbein/redmine_project_themes#1]
I try to update your plugin. 

> I think solve problem with alias_method_chain
> diff --git a/lib/redmine_project_themes/patches/projects_helper_patch.rb b/lib/redmine_project_themes/patches/projects_helper_patch.rb
> index 3ac9519..4eb26ee 100644
> --- a/lib/redmine_project_themes/patches/projects_helper_patch.rb
> +++ b/lib/redmine_project_themes/patches/projects_helper_patch.rb
> @@ -28,7 +28,9 @@ module RedmineProjectThemes
>          base.class_eval do
>            unloadable
> 
 -          alias_method_chain :project_settings_tabs, :project_themes_setting
 +          #alias_method_chain :project_settings_tabs, :project_themes_setting
 +         alias_method :project_settings_tabs_without_project_themes_setting, :project_settings_tabs
 +         alias_method :project_settings_tabs, :project_settings_tabs_with_project_themes_setting
>          end
>        end

But I don't success with error.

> sudo bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_project_themes
> (in /opt/redmine/redmine-4.1.0)
> rake aborted!
> StandardError: An error has occurred, this and all later migrations canceled:
> 
> Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
>   class AddProjectTheme < ActiveRecord::Migration[4.2]
> 
> Caused by:
> StandardError: Directly inheriting from ActiveRecord::Migration is not supported.

My config is 
Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               PostgreSQL

Can you help please?

**Comment by HugoHasenbein** [comment]
Hello,

thank you for your feedback.

You may try the following:

In addition to your alias_method amendments try to edit <plugin_directory>/redmine_project_themes/db/migrate/10_add_project_theme.rb like follows

- class AddProjectTheme < ActiveRecord::Migration
+class AddProjectTheme < ActiveRecord::Migration[5.1]

please replace '5.1' with the actual Rails version you use

If this works, please let me know

Best regards

Stephan

**Comment by CNPF** [comment]
@HugoHasenbein  no problem of 4.1.* branch.
Thank you so much
I try translate plugin in french.
