### ISSUE TITLE
french translation 

### ISSUE THREAD

**Issue by CNPF** [HugoHasenbein/redmine_project_themes#2]
French  translation is here attached. I add the label : label_save. it not exist in en.yml
[fr.yml.txt](https://github.com/HugoHasenbein/redmine_project_themes/files/4029968/fr.yml.txt)

**Comment by HugoHasenbein** [comment]
Hello,

thank you very much for your contribution. If the parens "[5.1]" did indeed solve the issue, then I will publish a version ready for redmine 4.xx soon and incorporate your French translation.

With respect to :label_save I have changed the symbol to :button_save - this way it will use the globally available translations from redmine.

Best regards

Stephan
