### ISSUE TITLE
Usage Error

### ISSUE THREAD

**Issue by yuxinvalo** [HugoHasenbein/redmine_project_themes#4]
Hello, 
When I install this plugin and test it, I can't click the project anymore, it show Internal Error, when I check production.log:  
![image](https://user-images.githubusercontent.com/9368058/75231467-c7bd7200-57b5-11ea-816a-cd8805ed2561.png)

What it means? I missi something?

**Comment by CNPF** [comment]
Hi,
Try

> git diff lib/redmine_project_themes/patches/redmine_theme_patch.rb
> diff --git a/lib/redmine_project_themes/patches/redmine_theme_patch.rb b/lib/redmine_project_themes/patches/redmine_theme_patch.rb
> index d225c6a..eae5fdc 100644
> --- a/lib/redmine_project_themes/patches/redmine_theme_patch.rb
> +++ b/lib/redmine_project_themes/patches/redmine_theme_patch.rb
> @@ -31,7 +31,7 @@ module RedmineProjectThemes
> 
> unless (instance_variable_defined?(:@current_theme) && instance_variable_defined?(:@current_project_for_theme) && @current_project_for_theme == @project )
>@current_project_for_theme = @project
> -@current_theme = (@project && @project.module_enabled?(:redmine_project_themes) && @project.ui_theme.present?) ? Redmine::Themes.theme(@project.ui_theme) : Redmine::Themes.theme(Setting.ui_theme)
> +@current_theme = (@project && @project.module_enabled?(:redmine_project_themes) && @project.theme_id.present?) ? Redmine::Themes.theme(@project.theme_id) : Redmine::Themes.theme(Setting.ui_theme)
> end
> 
>@current_theme

**Comment by yuxinvalo** [comment]
> Hi,
> Try
> 
> > git diff lib/redmine_project_themes/patches/redmine_theme_patch.rb
> > diff --git a/lib/redmine_project_themes/patches/redmine_theme_patch.rb b/lib/redmine_project_themes/patches/redmine_theme_patch.rb
> > index d225c6a..eae5fdc 100644
> > --- a/lib/redmine_project_themes/patches/redmine_theme_patch.rb
> > +++ b/lib/redmine_project_themes/patches/redmine_theme_patch.rb
> > @@ -31,7 +31,7 @@ module RedmineProjectThemes
> > unless (instance_variable_defined?(:@current_theme) && instance_variable_defined?(:@current_project_for_theme) && @current_project_for_theme == @project )
> > @current_project_for_theme = @project
> > -@current_theme = (@project && @project.module_enabled?(:redmine_project_themes) && @project.ui_theme.present?) ? Redmine::Themes.theme(@project.ui_theme) : Redmine::Themes.theme(Setting.ui_theme)
> > +@current_theme = (@project && @project.module_enabled?(:redmine_project_themes) && @project.theme_id.present?) ? Redmine::Themes.theme(@project.theme_id) : Redmine::Themes.theme(Setting.ui_theme)
> > end
> > @current_theme

Thinks, it seems that I didn't install any theme in my Redmine XD.. So the plugin can't find ui,.. But I advise if there is no theme to choose, make a warning or something rather than an error ...

**Comment by HugoHasenbein** [comment]
Dear Yuxinvalo,

thank you for your feedback - I will install a warning to prevent a fault.

best regards

Stephan
