### ISSUE TITLE
Theme project by default

### ISSUE THREAD

**Issue by CNPF** [HugoHasenbein/redmine_project_themes#5]
Dear Stephan
I'll try to defined a theme project by default. I think add a list in this page redmine/settings?tab=projects.
What do you think of this proposal?
Thanks

**Comment by HugoHasenbein** [comment]
Dear Richard,

the default should be the System Theme, what do you think?

best regards

Stephan

**Comment by CNPF** [comment]
Yes it's better. My proposal is related of my use of redmine.
Actually, by default, a new project use System Theme but the list isn't initalize.
Administration of theme project is opened only administrator. When a project manager create a new project, my filter dosnt show this.
By writing my answer, I found the solution to my problem. By applying a "not equal" filter, I resolve my poblem.
The issue is resolve for me
Thanks
